[package]
name = "sched_macros"
version = "0.1.1"
authors = ["Alex Norman <alex@x37v.info>"]
edition = "2018"

[dependencies]
syn = "0.15.22"
quote = "0.6.10"
proc-macro2 = "0.4.24"

[lib]
proc-macro = true
